//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class MS_News
    {
        public int Kid { get; set; }
        public string F_Title { get; set; }
        public int F_Taxis { get; set; }
        public int F_ClassKid { get; set; }
        public string F_LinkUrl { get; set; }
        public string F_FileUrl { get; set; }
        public string F_Author { get; set; }
        public string F_Souce { get; set; }
        public string F_Tags { get; set; }
        public Nullable<int> F_HitCount { get; set; }
        public Nullable<int> F_CommentCount { get; set; }
        public string F_Recommend { get; set; }
        public Nullable<int> F_IsAudit { get; set; }
        public Nullable<int> F_IsTop { get; set; }
        public Nullable<int> F_IsHot { get; set; }
        public Nullable<int> F_IsComment { get; set; }
        public Nullable<int> F_IsFiles { get; set; }
        public Nullable<int> F_IsRecycle { get; set; }
        public Nullable<int> F_IsRecommend { get; set; }
        public string F_SubContent { get; set; }
        public string F_Content { get; set; }
        public string F_PageTitle { get; set; }
        public string F_PageKeywords { get; set; }
        public string F_PageDescription { get; set; }
        public Nullable<int> F_AddAdminKid { get; set; }
        public Nullable<int> F_EditAdminKid { get; set; }
        public Nullable<System.DateTime> F_AddTime { get; set; }
        public Nullable<System.DateTime> F_EditTime { get; set; }
    }
}
