//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class MS_OnlineMessage
    {
        public int Kid { get; set; }
        public string F_TableType { get; set; }
        public Nullable<int> F_TableKid { get; set; }
        public string F_Title { get; set; }
        public string F_Content { get; set; }
        public Nullable<int> F_IsAudit { get; set; }
        public Nullable<int> F_UserKid { get; set; }
        public string F_Nickname { get; set; }
        public string F_UserFace { get; set; }
        public string F_UserAddress { get; set; }
        public string F_UserTel { get; set; }
        public string F_UserEmail { get; set; }
        public string F_UserIP { get; set; }
        public Nullable<int> F_ReKid { get; set; }
        public string F_ReContent { get; set; }
        public Nullable<System.DateTime> F_ReTime { get; set; }
        public Nullable<int> F_Dig { get; set; }
        public Nullable<int> F_Tread { get; set; }
        public int F_Taxis { get; set; }
        public Nullable<System.DateTime> F_AddTime { get; set; }
        public Nullable<System.DateTime> F_EditTime { get; set; }
        public Nullable<int> F_IsRecycle { get; set; }
    }
}
