//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class MS_Product
    {
        public int Kid { get; set; }
        public int F_ClassKid { get; set; }
        public string F_Title { get; set; }
        public string F_LinkUrl { get; set; }
        public string F_PicUrl { get; set; }
        public string F_Author { get; set; }
        public string F_Souce { get; set; }
        public string F_Tags { get; set; }
        public string F_Content { get; set; }
        public string F_NavContent { get; set; }
        public Nullable<int> F_Hits { get; set; }
        public int F_Taxis { get; set; }
        public Nullable<int> F_IsFiles { get; set; }
        public Nullable<int> F_IsTop { get; set; }
        public Nullable<int> F_IsComment { get; set; }
        public Nullable<int> F_IsRecommend { get; set; }
        public Nullable<int> F_IsSpecialoffer { get; set; }
        public Nullable<int> F_IsScarebuying { get; set; }
        public Nullable<int> F_IsSecKill { get; set; }
        public Nullable<int> F_Points { get; set; }
        public Nullable<int> F_Number { get; set; }
        public Nullable<decimal> F_Price { get; set; }
        public Nullable<decimal> F_Price_Mart { get; set; }
        public Nullable<decimal> F_Price_Specials { get; set; }
        public Nullable<decimal> F_Price_LimitBuy { get; set; }
        public Nullable<decimal> F_Price_SecKill { get; set; }
        public Nullable<System.DateTime> F_StartTime_SecKill { get; set; }
        public Nullable<System.DateTime> F_StartTime_LimitBuy { get; set; }
        public Nullable<System.DateTime> F_EndTime_LimitBuy { get; set; }
        public Nullable<int> F_IsWithProduct { get; set; }
        public string F_WithProductKid { get; set; }
        public Nullable<int> F_FreightPayer { get; set; }
        public Nullable<int> F_PostageKid { get; set; }
        public Nullable<System.DateTime> F_UpTime { get; set; }
        public Nullable<System.DateTime> F_DownTime { get; set; }
        public Nullable<int> F_SellNum { get; set; }
        public string F_AttributeClass { get; set; }
        public string F_Attribute { get; set; }
        public string F_PageTitle { get; set; }
        public string F_PageKeywords { get; set; }
        public string F_PageDescription { get; set; }
        public Nullable<System.DateTime> F_AddTime { get; set; }
        public Nullable<System.DateTime> F_EditTime { get; set; }
        public Nullable<int> F_AddAdminKid { get; set; }
        public Nullable<int> F_EditAdminKid { get; set; }
        public Nullable<int> F_IsAudit { get; set; }
        public Nullable<int> F_IsRecycle { get; set; }
        public string F_YunFile { get; set; }
    }
}
