//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class MS_UserSpreadEffect
    {
        public int Kid { get; set; }
        public string F_OrderNumber { get; set; }
        public Nullable<int> F_SpreadKid { get; set; }
        public string F_UserName { get; set; }
        public Nullable<decimal> F_TotalSum { get; set; }
        public string F_CommissionRate { get; set; }
        public Nullable<decimal> F_Commission { get; set; }
        public Nullable<int> F_Clearing { get; set; }
        public Nullable<int> F_IsRecycle { get; set; }
    }
}
