//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShuEntities : DbContext
    {
        public ShuEntities()
            : base("name=ShuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MS_ADClass> MS_ADClass { get; set; }
        public virtual DbSet<MS_Admin> MS_Admin { get; set; }
        public virtual DbSet<MS_AdminAction> MS_AdminAction { get; set; }
        public virtual DbSet<MS_AdminModule> MS_AdminModule { get; set; }
        public virtual DbSet<MS_AdminRole> MS_AdminRole { get; set; }
        public virtual DbSet<MS_AdminRoleMenu> MS_AdminRoleMenu { get; set; }
        public virtual DbSet<MS_AdminRoleModule> MS_AdminRoleModule { get; set; }
        public virtual DbSet<MS_AdminRoleTable> MS_AdminRoleTable { get; set; }
        public virtual DbSet<MS_Candidates> MS_Candidates { get; set; }
        public virtual DbSet<MS_Config> MS_Config { get; set; }
        public virtual DbSet<MS_Department> MS_Department { get; set; }
        public virtual DbSet<MS_Dept> MS_Dept { get; set; }
        public virtual DbSet<MS_Download> MS_Download { get; set; }
        public virtual DbSet<MS_DownloadClass> MS_DownloadClass { get; set; }
        public virtual DbSet<MS_Express> MS_Express { get; set; }
        public virtual DbSet<MS_FileUrl> MS_FileUrl { get; set; }
        public virtual DbSet<MS_JobTitle> MS_JobTitle { get; set; }
        public virtual DbSet<MS_Link> MS_Link { get; set; }
        public virtual DbSet<MS_LinkClass> MS_LinkClass { get; set; }
        public virtual DbSet<MS_Log> MS_Log { get; set; }
        public virtual DbSet<MS_Login> MS_Login { get; set; }
        public virtual DbSet<MS_MailTemplate> MS_MailTemplate { get; set; }
        public virtual DbSet<MS_Menu> MS_Menu { get; set; }
        public virtual DbSet<MS_MenuPageRelation> MS_MenuPageRelation { get; set; }
        public virtual DbSet<MS_ModuleAction> MS_ModuleAction { get; set; }
        public virtual DbSet<MS_News> MS_News { get; set; }
        public virtual DbSet<MS_NewsClass> MS_NewsClass { get; set; }
        public virtual DbSet<MS_Online> MS_Online { get; set; }
        public virtual DbSet<MS_OnlineMessage> MS_OnlineMessage { get; set; }
        public virtual DbSet<MS_Order> MS_Order { get; set; }
        public virtual DbSet<MS_OrderDetail> MS_OrderDetail { get; set; }
        public virtual DbSet<MS_Payment> MS_Payment { get; set; }
        public virtual DbSet<MS_Product> MS_Product { get; set; }
        public virtual DbSet<MS_ProductAttribute> MS_ProductAttribute { get; set; }
        public virtual DbSet<MS_ProductAttributeClass> MS_ProductAttributeClass { get; set; }
        public virtual DbSet<MS_ProductClass> MS_ProductClass { get; set; }
        public virtual DbSet<MS_ProductGoods> MS_ProductGoods { get; set; }
        public virtual DbSet<MS_ProductSpec> MS_ProductSpec { get; set; }
        public virtual DbSet<MS_RecommendPosition> MS_RecommendPosition { get; set; }
        public virtual DbSet<MS_Recruitment> MS_Recruitment { get; set; }
        public virtual DbSet<MS_RelationAttributeTable> MS_RelationAttributeTable { get; set; }
        public virtual DbSet<MS_ReWrite> MS_ReWrite { get; set; }
        public virtual DbSet<MS_RSS> MS_RSS { get; set; }
        public virtual DbSet<MS_Spec> MS_Spec { get; set; }
        public virtual DbSet<MS_Stat> MS_Stat { get; set; }
        public virtual DbSet<MS_Survey> MS_Survey { get; set; }
        public virtual DbSet<MS_SurveyClass> MS_SurveyClass { get; set; }
        public virtual DbSet<MS_SurveyItem> MS_SurveyItem { get; set; }
        public virtual DbSet<MS_SurveyOption> MS_SurveyOption { get; set; }
        public virtual DbSet<MS_SurveyUser> MS_SurveyUser { get; set; }
        public virtual DbSet<MS_SurveyUserOption> MS_SurveyUserOption { get; set; }
        public virtual DbSet<MS_Tags> MS_Tags { get; set; }
        public virtual DbSet<MS_Topic> MS_Topic { get; set; }
        public virtual DbSet<MS_TopicPart> MS_TopicPart { get; set; }
        public virtual DbSet<MS_TopicPartContent> MS_TopicPartContent { get; set; }
        public virtual DbSet<MS_User> MS_User { get; set; }
        public virtual DbSet<MS_User_Oauth> MS_User_Oauth { get; set; }
        public virtual DbSet<MS_User_Oauth_App> MS_User_Oauth_App { get; set; }
        public virtual DbSet<MS_UserAddress> MS_UserAddress { get; set; }
        public virtual DbSet<MS_UserFavorite> MS_UserFavorite { get; set; }
        public virtual DbSet<MS_UserGroup> MS_UserGroup { get; set; }
        public virtual DbSet<MS_UserSpread> MS_UserSpread { get; set; }
        public virtual DbSet<MS_UserSpreadEffect> MS_UserSpreadEffect { get; set; }
        public virtual DbSet<MS_Video> MS_Video { get; set; }
        public virtual DbSet<MS_VideoClass> MS_VideoClass { get; set; }
        public virtual DbSet<SequenceNumber> SequenceNumber { get; set; }
        public virtual DbSet<MS_AD> MS_AD { get; set; }
        public virtual DbSet<View_MS_AD> View_MS_AD { get; set; }
    
        public virtual ObjectResult<GetSequenceNumber_Result> GetSequenceNumber(string code, Nullable<int> count)
        {
            var codeParameter = code != null ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(string));
    
            var countParameter = count.HasValue ?
                new ObjectParameter("Count", count) :
                new ObjectParameter("Count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSequenceNumber_Result>("GetSequenceNumber", codeParameter, countParameter);
        }
    
        public virtual ObjectResult<SP_FindColumnInDB_Result> SP_FindColumnInDB(string value)
        {
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FindColumnInDB_Result>("SP_FindColumnInDB", valueParameter);
        }
    
        public virtual int SP_FindValueInDB(string value)
        {
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_FindValueInDB", valueParameter);
        }
    
        [DbFunction("ShuEntities", "GetChildID_ADClass")]
        public virtual IQueryable<GetChildID_ADClass_Result> GetChildID_ADClass(Nullable<int> kID)
        {
            var kIDParameter = kID.HasValue ?
                new ObjectParameter("KID", kID) :
                new ObjectParameter("KID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetChildID_ADClass_Result>("[ShuEntities].[GetChildID_ADClass](@KID)", kIDParameter);
        }
    
        [DbFunction("ShuEntities", "GetChildID_AdminRole")]
        public virtual IQueryable<GetChildID_AdminRole_Result> GetChildID_AdminRole(Nullable<int> kID)
        {
            var kIDParameter = kID.HasValue ?
                new ObjectParameter("KID", kID) :
                new ObjectParameter("KID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetChildID_AdminRole_Result>("[ShuEntities].[GetChildID_AdminRole](@KID)", kIDParameter);
        }
    
        [DbFunction("ShuEntities", "GetChildID_DownloadClass")]
        public virtual IQueryable<GetChildID_DownloadClass_Result> GetChildID_DownloadClass(Nullable<int> kID)
        {
            var kIDParameter = kID.HasValue ?
                new ObjectParameter("KID", kID) :
                new ObjectParameter("KID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetChildID_DownloadClass_Result>("[ShuEntities].[GetChildID_DownloadClass](@KID)", kIDParameter);
        }
    
        [DbFunction("ShuEntities", "GetChildID_LinkClass")]
        public virtual IQueryable<GetChildID_LinkClass_Result> GetChildID_LinkClass(Nullable<int> kID)
        {
            var kIDParameter = kID.HasValue ?
                new ObjectParameter("KID", kID) :
                new ObjectParameter("KID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetChildID_LinkClass_Result>("[ShuEntities].[GetChildID_LinkClass](@KID)", kIDParameter);
        }
    
        [DbFunction("ShuEntities", "GetChildID_NewsClass")]
        public virtual IQueryable<GetChildID_NewsClass_Result> GetChildID_NewsClass(Nullable<int> kID)
        {
            var kIDParameter = kID.HasValue ?
                new ObjectParameter("KID", kID) :
                new ObjectParameter("KID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetChildID_NewsClass_Result>("[ShuEntities].[GetChildID_NewsClass](@KID)", kIDParameter);
        }
    
        [DbFunction("ShuEntities", "GetChildID_ProductClass")]
        public virtual IQueryable<GetChildID_ProductClass_Result> GetChildID_ProductClass(Nullable<int> kID)
        {
            var kIDParameter = kID.HasValue ?
                new ObjectParameter("KID", kID) :
                new ObjectParameter("KID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetChildID_ProductClass_Result>("[ShuEntities].[GetChildID_ProductClass](@KID)", kIDParameter);
        }
    
        [DbFunction("ShuEntities", "GetChildID_VideoClass")]
        public virtual IQueryable<GetChildID_VideoClass_Result> GetChildID_VideoClass(Nullable<int> kID)
        {
            var kIDParameter = kID.HasValue ?
                new ObjectParameter("KID", kID) :
                new ObjectParameter("KID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetChildID_VideoClass_Result>("[ShuEntities].[GetChildID_VideoClass](@KID)", kIDParameter);
        }
    
        [DbFunction("ShuEntities", "GetParentID_AdminRole")]
        public virtual IQueryable<GetParentID_AdminRole_Result> GetParentID_AdminRole(Nullable<int> kid)
        {
            var kidParameter = kid.HasValue ?
                new ObjectParameter("Kid", kid) :
                new ObjectParameter("Kid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetParentID_AdminRole_Result>("[ShuEntities].[GetParentID_AdminRole](@Kid)", kidParameter);
        }
    
        [DbFunction("ShuEntities", "GetParentID_NewsClass")]
        public virtual IQueryable<GetParentID_NewsClass_Result> GetParentID_NewsClass(Nullable<int> kid)
        {
            var kidParameter = kid.HasValue ?
                new ObjectParameter("Kid", kid) :
                new ObjectParameter("Kid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetParentID_NewsClass_Result>("[ShuEntities].[GetParentID_NewsClass](@Kid)", kidParameter);
        }
    
        [DbFunction("ShuEntities", "GetParentID_ProductClass")]
        public virtual IQueryable<GetParentID_ProductClass_Result> GetParentID_ProductClass(Nullable<int> kid)
        {
            var kidParameter = kid.HasValue ?
                new ObjectParameter("Kid", kid) :
                new ObjectParameter("Kid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetParentID_ProductClass_Result>("[ShuEntities].[GetParentID_ProductClass](@Kid)", kidParameter);
        }
    
        [DbFunction("ShuEntities", "GetTreeID_AdminRole")]
        public virtual IQueryable<GetTreeID_AdminRole_Result> GetTreeID_AdminRole(Nullable<int> kid)
        {
            var kidParameter = kid.HasValue ?
                new ObjectParameter("Kid", kid) :
                new ObjectParameter("Kid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetTreeID_AdminRole_Result>("[ShuEntities].[GetTreeID_AdminRole](@Kid)", kidParameter);
        }
    }
}
