//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shu.Model
{
    
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class View_MS_AD
    {
        public int Kid { get; set; }
        public int F_ClassKid { get; set; }
        public string F_Type { get; set; }
        public string F_Title { get; set; }
        public string F_CodeID { get; set; }
        public string F_LinkUrl { get; set; }
        public string F_ImageUrl { get; set; }
        public string F_Explain { get; set; }
        public string F_CodeText { get; set; }
        public int F_Width { get; set; }
        public int F_Height { get; set; }
        public int F_Taxis { get; set; }
        public int F_Enabled { get; set; }
        public Nullable<System.DateTime> F_StartTime { get; set; }
        public Nullable<System.DateTime> F_EndTime { get; set; }
        public Nullable<System.DateTime> F_AddTime { get; set; }
        public Nullable<System.DateTime> F_EditTime { get; set; }
        public int F_ClickVolume { get; set; }
        public Nullable<int> F_AddAdminKid { get; set; }
        public Nullable<int> F_EditAdminKid { get; set; }
        public Nullable<int> F_IsRecycle { get; set; }
    }
}
